-- 서비스 체험용 데모 도서관 후보군.
--
-- 사서가 CSV를 올리기 전에도 추천·오늘의 책·비교 흐름을 확인할 수 있도록 미리 넣어 둔다.
-- 지어낸 데이터가 아니라 정보나루 실데이터이며, HiddenBookCollector의 API 경로와 같은 규칙으로 골랐다:
--   부산광역시 강서도서관(121020)의 2025-08-15~2026-08-15 장서 목록(itemSrch)에서
--   같은 기간 대출 순위 상위 5,000권(loanItemSrch)에 들지 못한 장서를 추린 뒤,
--   정보나루 상세(srchDtlList)에 소개글이 있는 도서만 남겼다.
-- 추천 이유(reason)는 비워 둔다. 화면에 처음 필요할 때 생성해 저장한다.

INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9788964965504', '121020', '부산광역시 강서도서관', '당근 사러 갔다가 앵무새 사 왔어요!', '마이클 로젠', 'https://shopping-phinf.pstatic.net/main_6056845/60568459323.20260623201836.jpg', 0, 80, 'DEMO_SEED', '843-로74당', '[강서구]어린이자료실', '2026년 안데르센 상 수상 작가 마이클 로젠그리고 케이트 그린어웨이 상 수상 작가 헬린 옥슨버리,《곰 사냥을 떠나자》 콤비가 36년 만에 다시 만나다!2026년 한스 크리스티안 안데르센 상 수상에 빛나는 마이클 로젠이 《곰 사냥을 떠나자》 이후 36년 만에 헬렌 옥슨버리와 의기투합하여 만들어 낸 《당근 사러 갔다가 앵무새 사 왔어요!》. 영국 아동문학계를 대표하는 두 작가의 다시 없을 환상적인 하모니를 엿볼 수 있는 이 책은, 마이클 로젠이 안데르센 상을 수상한 뒤에 선보이는 첫 번째 신간이자 2026년 브리티시 북 어워드 어린이 논픽션&그림책 부문 수상작이라 그 의미가 더욱 높다. 전작에서는 감정의 점증적 표현에 집중했다면, 이번 《당근 사러 갔다가 앵무새 사 왔어요!》에서는 기발하고도 발칙한 감정의 반전에 집중한다. 글 작가 특유의 재치 있고 운율이 넘치게 이어지는 말놀이는 긴장감과 웃음을 함께 자아낸다. 통통 튕기는 글에 섬세한 수채화가 더해져 글과 그림의 밸런스가 그야말로 압도적인 이 책은 요리조리 변덕스러운 어린이 독자들의 마음을 단번에 사로잡는다. 또한 이야기 중간중간 영어 발음의 연결성을 절묘하게 녹아내어 한국어와 영어 두 마리 토끼를 모두 잡게 한다.', NULL, NOW(6), NOW(6));
INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9791167903754', '121020', '부산광역시 강서도서관', '이름 없는 것들의 밤', '정보라 (지은이)', 'https://image.aladin.co.kr/product/39827/79/cover200/k382130711_1.jpg', 0, 68, 'DEMO_SEED', '813.6-정45이B', '[강서구]종합자료실', '정보라의 연작소설집 『이름 없는 것들의 밤』이 현대문학에서 출간되었다. &lt;현대문학 핀 시리즈&gt; 장르선의 시작을 알린 『밤이 오면 우리는』과 『현대문학』 2024년 12월호, 2026년 3월호에 수록된 두 편의 중편소설을 함께 엮은 연작소설집이다.', NULL, NOW(6), NOW(6));
INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9791170833291', '121020', '부산광역시 강서도서관', '영혼의 참된 자유', '로완 윌리엄스 (지은이), 민경찬 (옮긴이)', 'https://image.aladin.co.kr/product/39137/1/cover200/k852137654_1.jpg', 0, 66, 'DEMO_SEED', '233.696-윌298영', '[강서구]종합자료실', '자신의 힘으로 모든 것을 통제할 수 있다는 헛된 환상과 세상을 마음대로 소비할 수 있다는 탐욕에 갇혀 ‘나’를 잃어버린 현대인. 로완 윌리엄스는 이들이 거짓 자아를 벗고 영혼의 참된 자유를 찾을 수 있도록 초기 그리스도교 전통을 탐구한다.', NULL, NOW(6), NOW(6));
INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9791193939666', '121020', '부산광역시 강서도서관', '독서의 기술 - 책은 어떻게 삶의 무기가 되는가', '고명환', 'https://shopping-phinf.pstatic.net/main_6058347/60583478236.20260624104607.jpg', 0, 72, 'DEMO_SEED', '029.4-고34독', '[강서구]종합자료실', '‘올해의 작가상’ 수상, 해외 5개국 판권 수출, 요식업 CEO 등 개그맨에서 작가이자 강연가, 사업가로 완벽하게 변신한 저자는 이 모든 것이 독서 덕분이라 말한다. 어떻게 독서가 삶의 무기가 되고 질문에 대한 해답을 주는지 『독서의 기술』을 통해 그간의 독서 경험을 가감 없이 펼쳐낸다.', NULL, NOW(6), NOW(6));
INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9788964375129', '121020', '부산광역시 강서도서관', '평등한 평범 - 차별금지법이 꿈꾸는 세상', '장혜영', 'https://shopping-phinf.pstatic.net/main_6067761/60677618007.20260701162201.jpg', 0, 80, 'DEMO_SEED', '342.1-장94평', '[강서구]종합자료실', '“나는 평범함을 되찾고 싶어 이 책을 쓰기로 했다.”장애가 있어도, 가난해도, 못 배워도, 피부색과 외모와 성별과 성적 지향이 달라도, 부모를 잘못 만나도, 살다가 불운을 만나게 된다 해도 모두가 함께 무사히 할머니 할아버지가 되어 가는 미래를 갖고 싶어 시작한 차별금지법 제정 분투기발달장애인 동생의 ‘생각 많은 둘째 언니’,다큐멘터리 〈어른이 되면〉의 감독,책 『어른이 되면』의 저자.노래 〈무사히 할머니가 될 수 있을까〉를 부른 뮤지션,21대 국회에서 차별금지법을 대표 발의했던 전직 국회의원,그리고 지금도 차별금지법 제정을 외치고 있는 재야의 목소리.장혜영의 이 모든 정체성이 일관되게 터벅터벅 이어져 도달한 한 권의 기록.★ “우리는 모두 이상하다는 점에서 평범하고, 그래서 평등하다”거리에서 무심하게 서로의 얼굴을 스쳐 지나가는 우리 모두는 어딘가 조금씩 이상한 사람들이다. 나, 그리고 나와 가까운 사람들이 평소에 하는 이상한 행동들을 가만히 떠올려 보면 금방 공감할 수 있다. 놀랍게도 이 비범한 사람들 대부분은 평소에 더할 나위 없이 평범하다. 그런 의미에서 이상함만큼 평범한 것은 없다. 하지만 평범함에 대한 사회적 기준을 고려하면 이야기가 달라진다. 그저 평범하게 살기 위해서라도 우리는 비범해져야 하고, 때로는 서로를 문제의 원인으로 규정하고 증오하고 차별하고 나아가 폭력을 행사하는 데까지 이르기 때문이다. 그렇다. 이 책의 키워드는 ‘평범함’이다.★ ‘모두의 평범함’을 되찾기 위한 수단으로서의 차별금지법평범하다는 말 안에는 ‘다수’라는 의미가 은연중에 포함되어 있지만 현실에서는 역설적으로 ‘평범한 사람들’이 점점 줄어들고 있다. 저자는 차별금지법이 “평범함을 다수의 것으로 되찾기 위한 것”이라고 말한다. 이때 다수는 평범한 삶을 염원하는 모든 사람을 넉넉히 포함하는 다수다. 나아가 한때는 평범하게 여겨졌던 신분제가, 남존여비가, 심지어 순장이라는 풍습마저도 이제는 사라졌다는 점에서 평범함의 풍경은 사람들이 용기 내어 변화를 선택하는 만큼 달라질 수 있으며, 차별금지법은 이런 평범함의 진취적 가능성을 포함한다는 점이 중요하다.★ 차별금지법에 대한 이해와 오해에 대하여차별금지법에는 차별 행위에 대한 처벌 조항이 있을까? 대답은 ‘아니요’다. 저자는 입법자로서 법안을 대표 발의하며 쌓았던 실력을 십분 발휘하여 “차별금지법에 대한 오해와 이해”를 공들여 알기 쉽게 설명한다. 그는 잘못 알려진 바와 달리, 이 법은 차별에 대한 처벌을 통해 사람들을 교화하는 법이 아니라, 차별에 대한 시정 권고를 통해, 사람들에게 지금까지 몰랐던 차별을 알려주고 스스로 고칠 수 있도록 길을 안내하는 법이라는 점을 특히 강조한다. 시민들이 차별을 저지르는 이유는 그것이 차별임을 모르기 때문이며, 만일 그것이 차별임을 알게 된다면 시정할 것이라는, 변화에 대한 신뢰를 전제로 하기 때문이다.★ 그래서, 그가 발의한 포괄적 차별금지법은 어떻게 됐을까?: 국회에서 경험한 ‘이론과 실제’의 좌충우돌 생생한 이야기차별금지법은 19년 동안 14차례 발의되었지만, 한 번도 국회에서 심의된 적이 없다. 국회의원 장혜영이 대표 발의한 법안이 일곱 번째 발의였으므로, 당연히 심의되지 못했고 임기 만료로 자동 폐기되었다. 이 좌충우돌 일곱 번째 발의의 기록과, 국회에서 경험한 ‘이론과 실제’의 생생한 이야기가 흥미진진하게 펼쳐진다. “차별금지법 제정을 위한 우리의 노력이 펄떡이며 살아 숨 쉬는 현재진행형이 되기 위해서는 과거의 도전을 차분히 돌아보고 스스로를 가다듬어야 하기 때문”이다.', NULL, NOW(6), NOW(6));
INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9791124121115', '121020', '부산광역시 강서도서관', '키는 타이밍입니다 :성장클리닉을 찾기 전 알아야 할 키 성장과 성조숙증', '박승찬 지음', 'https://shopping-phinf.pstatic.net/main_6060150/60601501748.20260625183547.jpg', 0, 80, 'DEMO_SEED', '511.1682-박57키', '[강서구]종합자료실', '우리 아이 평생 키, 기다리는 것보다 성장 타이밍을 살피는 일이 먼저입니다〈강남 하이키 성장클리닉〉 원장의 30년 성장 골든타임 관리법“키는 유전 아닌가요?”부모님들이 흔히 하는 말입니다. 하지만 이 말은 반은 맞고 반은 틀립니다. 키의 약 70%는 유전의 영향을 받지만, 나머지 30%는 영양과 운동, 수면을 비롯한 성장 환경과 생활 습관에 따라 달라질 수 있습니다. 부모가 아이를 위해 해줄 수 있는 일이 분명히 남아 있다는 뜻입니다.지금 아이들은 영양 과잉과 운동 부족, 학업 스트레스, 스마트폰으로 인한 수면 부족, 빨라지는 사춘기와 성조숙증 등 부모 세대와는 전혀 다른 성장 환경에 놓여있습니다. 따라서 지금 또래보다 크다고 안심해서도, 조금 작다고 “때가 되면 크겠지.”라며 기다려서도 안 됩니다. 성장에는 반드시 살펴야 할 시기가 있으며, 그 타이밍을 놓치면 되돌리기 어려울 수 있기 때문입니다.30년간 아이들의 성장을 진료해 온 저자는 부모가 아이의 성장 신호를 제대로 살피고, 가장 중요한 시기에 필요한 선택을 할 수 있도록 이 책을 썼습니다. 현재 아이의 성장 상태를 확인하는 법부터 영양·수면·운동·체중 관리법, 성장클리닉을 찾아야 할 시점, 성조숙증 신호까지 부모가 아이의 성장에 관해 꼭 알아야 할 내용을 담았습니다.부모가 아이의 키를 마음대로 정할 수는 없지만, 아이의 성장 잠재력을 충분히 펼치도록 도울 수는 있습니다. 그 시작은 아이의 성장 타이밍을 놓치지 않는 것입니다.', NULL, NOW(6), NOW(6));
INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9791194828396', '121020', '부산광역시 강서도서관', '느릿느릿 할머니의 빨간 떡볶이', '유진', 'https://shopping-phinf.pstatic.net/main_6055035/60550358621.20260622123930.jpg', 0, 80, 'DEMO_SEED', '813.8-유78느', '[강서구]어린이자료실', '느릿느릿 할머니의 빨간 떡볶이…… 오늘 안에 맛볼 수 있을까?느릿느릿 할머니의 빨간 떡볶이집은 오늘도 영업 중이다. 딸랑! 단골 민준이와 민준이 엄마가 들어온다. 반갑게 맞이한 할머니가 움직이기 시작한다. 터덕 터덕 터덕 걸어가 쪼로록 컵에 물을 따른 뒤 터덕 찰랑 터덕 찰랑 더턱 찰랑. 테이블로 돌아와 주문을 받는다. “떡볶이 일인분하고 순대 주세요. 라면 사리도 넣어서요.” 터덕 탁 터덕. 부스럭부스럭. 떡볶이는 준비 중이다. 차르르. 타다다닥. 철퍽. 휘익휘익. 아직 끓지도 않았다. 그때 또 한 번 딸랑! 덩치 큰 아저씨 손님이 들어온다. “할머니~ 떡볶이 매운맛으로 주세요. 순대도 하나 주시고요.” 주문이 하나 더 추가된다. 느릿느릿 할머니의 빨간 떡볶이… 오늘 안에 맛볼 수 있을까? 할머니의 속도는 우리가 채운다!『듣고 싶은 말』로 독자들 마음속 어린아이를 위로했던 유진 작가가 『느릿느릿 할머니의 빨간 떡볶이』로 다시 한 번 추억의 맛을 선보인다. 떡볶이의 달인 같은 풍모로 손님들이 몰려도 급할 것 없이 느릿느릿 움직이는 할머니와 기다리다 못해 할머니의 속도를 알아서 눈치껏 채워 나가는 손님들의 오묘한 조화가 웃음을 자아내는 『느릿느릿 할머니의 빨간 떡볶이』는 어른과 어린이 독자가 함께 공감하고 저마다의 추억을 떠올릴 그림책이다. 어딘가 심드렁해 보이기도 하는 할머니이지만 꼬마 단골 민준이의 이름을 기억하고, 이미 어른이 된 손님의 어린 시절 입맛을 떠올려 장난스럽게 대하는 모습이 유쾌하고 다정한 분식집 할머니를 생각나게 한다. 어린 민준이와 민준이 엄마, 덩치 큰 아저씨, 게임에 빠져 있는 남학생들, 발랄한 여자 손님들까지 알아서 척척 할머니를 거드는 이유는 단 하나! 시간과 노동력을 들여서라도 먹고 싶은 떡볶이 때문이다. 누구에게나 하나쯤 시름을 잊게 하고 용기와 기운을 북돋아 주는 대상이 있을 것이다. 어릴 때 먹었던 학교 앞 떡볶이나 엄마가 말아 주던 집김밥 한 줄, 함께 자라 온 사랑스러운 반려동물이나 시간이 지나도 잊히지 않는 책 한 권…… 이런 존재들 덕에 우리는 오늘도 살아갈 힘을 얻는다. 몸과 마음을 위로해 주는 소중한 기억을 떠올리게 하는 그림책『느릿느릿 할머니의 빨간 떡볶이』와 함께 세대를 이어 갈 추억을 만들어 보는 건 어떨까?  소리까지 맛있는 『느릿느릿 할머니의 빨간 떡볶이』  작가가 처음 애니메이션으로 기획한 이야기이기도 한 『느릿느릿 할머니의 빨간 떡볶이』는 분할된 화면 구성과 리듬감을 살린 의성어 의태어로 독자의 몰입을 이끄는 재치 넘치는 그림책이다. 실제 떡볶이집에 와 있는 것 같은 현장감이 돋보이는데, 무서운 영화를 소리 없이 보면 밋밋하게 느껴지는 것처럼 딸랑, 터덕터덕, 쪼르륵, 찰랑, 부스럭, 차르르, 휘익휘익, 부글부글 등의 표현이 없는 『느릿느릿 할머니의 빨간 떡볶이』는 떡이 없는 떡볶이나 다름없을 것이다. 네모 칸으로 경계를 지어 표현한 각 소리들이 점점 더 잘게 반복돼 가며 정신없이 쌓이다가 땡 하는 소리와 함께 완성된 떡볶이로 상황이 정리되는 대목은 긴장 뒤 이완에서 오는 안도감으로 독자의 호흡을 사로잡는다. 마치 사물놀이에서 휘모리로 몰아치다 한순간 고요해지며 맺음 장단으로 마무리되는 대목과 비슷하게 느껴진다. 배달과 포장이 안 돼도 줄서서 찾아가고픈 오래된 맛집의 진가를 느끼게 해 주는 『느릿느릿 할머니의 빨간 떡볶이』는 유쾌한 캐릭터와 박진감 넘치는 리듬감에 향수 어린 소재로 새로운 매력을 보여 주는 그림책이다. 『느릿느릿 할머니의 빨간 떡볶이』를 펼치고 맛있고 배부른 그림책 속으로 빠져 보자.', NULL, NOW(6), NOW(6));
INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9791171259458', '121020', '부산광역시 강서도서관', '너는 무엇을 알고 있니?', '아리아나 필즈 (지은이), 아라셀리스 거메이 (그림), 서남희 (옮긴이)', 'https://image.aladin.co.kr/product/39772/39/cover200/k072130103_1.jpg', 0, 62, 'DEMO_SEED', '808-네44', '[강서구]어린이자료실', '사랑이 이곳저곳을 돌아다니며 다양한 존재에게 “너는 무엇을 알고 있니?”라는 질문을 던지며 대답을 듣는 이야기다. 사랑의 여정을 따라가다 보면 자연스럽게 세상의 다양한 존재의 대답을 들을 수 있다.', NULL, NOW(6), NOW(6));
INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9791191994513', '121020', '부산광역시 강서도서관', '추추의 집밥 클래스 - 누가 만들어도 참 쉽고 맛있다', '추재현', 'https://shopping-phinf.pstatic.net/main_6056846/60568460790.20260623201908.jpg', 0, 71, 'DEMO_SEED', '594.51-추73집', '[강서구]종합자료실', '유튜브 85만 명, 인스타그램 23만 명, 틱톡 40만 명의 구독자를 달성하며 모든 플랫폼의 시청자를 사로잡은 ''한식 올라운더'' 추추의 첫 요리책이 출간됐다. 한식을 배우고 연구하기 위해 어디든 달려들어 몸을 사리지 않은 그의 드디어 완성된 레시피를 한 권의 책으로 만나볼 수 있다.', NULL, NOW(6), NOW(6));
INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9788955969795', '121020', '부산광역시 강서도서관', '먹는 게 다 화학입니다 - 헷갈리는 정보 속에서 덜 속고 더 건강하게 먹기 위한', '손미현 (지은이)', 'https://image.aladin.co.kr/product/39151/86/cover200/8955969791_1.jpg', 0, 80, 'DEMO_SEED', '517.5-손38먹', '[강서구]종합자료실', '칼로리, 혈당지수, 나트륨, 트랜스지방, 아스파탐… 마트에서 제품 하나를 집어 들면 어김없이 빽빽한 영양 성분표가 눈에 들어온다. 한 번 훑다가 그냥 제자리에 내려놓은 경험, 누구나 한 번쯤 있지 않을까. 먹거리에 관한 정보는 넘쳐나지만 "이건 먹으면 안 돼", "이 성분은 무조건 피해"라는 말들이 쏟아질수록 오히려 음식 앞에서 기쁨보다 피로감과 죄책감을 먼저 느끼게 된다. 그 혼란을 정리해 주기 위해 ''프로 다이어터'' 화학자, 손미현 교수가 나섰다.', NULL, NOW(6), NOW(6));
INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9791199757646', '121020', '부산광역시 강서도서관', '인간을 인간답게 만드는 불완전함에 대하여', '팀 하포드 지음 ;윤영삼 옮김', 'https://image.aladin.co.kr/product/39153/34/cover200/k062138867_1.jpg', 0, 57, 'DEMO_SEED', '001.3-하895인', '[강서구]종합자료실', '알고리즘 시대의 혼란 속에서 인간의 불완전함을 다시 묻는다. 팀 하포드는 즉흥성과 회복탄력성이 만든 성취를 통해, 효율 너머 인간다운 삶의 조건을 탐구한다.', NULL, NOW(6), NOW(6));
INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9791130681887', '121020', '부산광역시 강서도서관', '독후감 숙제가 끝나지 않아', '누카가 미오 (지은이), 토티 (그림), 김지영 (옮긴이)', 'https://image.aladin.co.kr/product/39738/21/cover200/k652130909_1.jpg', 0, 58, 'DEMO_SEED', '833.8-누872독', '[강서구]어린이자료실', 'AI가 거듭 발전할수록 글쓰기의 가치는 더욱 빛을 발한다. 『독후감 숙제가 끝나지 않아』는 다섯 명의 초등학생이 독후감을 쓰며 자신의 진짜 속마음과 마주하는 이야기다.', NULL, NOW(6), NOW(6));
INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9791193024348', '121020', '부산광역시 강서도서관', '자네 이름은 산초가 좋겠다 :가언 단편집', '지은이: 가언', 'https://image.aladin.co.kr/product/32935/98/cover/k632936947_1.jpg', 0, 63, 'DEMO_SEED', '813.6-안74쇼', '[강서구]종합자료실', '안전가옥 쇼-트 시리즈 스물세 번째 책. 우리가 너무도 잘 아는 세 편의 고전 문학 《노인과 바다》, 《돈키호테》, 《80일간의 세계 일주》를 웹소설과 판타지 소설의 문법으로 재해석한 작가 가언의 첫 단편집이다.', NULL, NOW(6), NOW(6));
INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9791190539296', '121020', '부산광역시 강서도서관', '나의 부치 엄마', '황후이전', 'https://shopping-phinf.pstatic.net/main_6055172/60551725655.20260623071254.jpg', 0, 80, 'DEMO_SEED', '823.7-황96나', '[강서구]종합자료실', '베를린국제영화제 테디상 수상, 서울국제여성영화제 나프어워드 수상, 타이베이영화제 최우수 다큐멘터리상 수상 등 전 세계 유수의 영화제를 휩쓸며 ‘가족의 형태’에 대한 근원적인 질문을 던졌던 영화 「일상 대화」. 그 이십 년의 기록이 한 권의 진실한 에세이 『나의 부치 엄마』로 재탄생했다.작가는 자신의 어머니를 ‘부치(Butch) 엄마’, 여자를 좋아하는 엄마라고 부른다. 이 책은 레즈비언 엄마를 둔 딸의 눈으로 시작해 결국 관계와 화해에 대한 이야기를 건넨다. 작가는 자신을 옥죄던 비밀의 껍질을 깨고, 비로소 엄마라는 한 인간을 온전히 받아들인다. 허우샤오센(영화감독), 천쉐·지다웨이(작가), 리 코토미(소설가) 등 동아시아 문화계가 주목한 이 찬란한 기록은 ‘정상 가족’의 신화에 갇혀 고립된 오늘날의 독자들에게 뜨거운 용기와 힘을 건넬 것이다.', NULL, NOW(6), NOW(6));
INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9791173326639', '121020', '부산광역시 강서도서관', '혼자 죽는 사회 - 사회적 부검으로 들여다본 한국인의 고독사', '송인주 (지은이)', 'https://image.aladin.co.kr/product/39820/4/cover200/k062130603_1.jpg', 0, 68, 'DEMO_SEED', '332.277-송68혼', '[강서구]종합자료실', '한국 최초로 고독사 통계와 판정 기준을 마련한 사회복지 연구자이자 스스로랩 대표 송인주의 첫 책이다. 저자는 2016년부터 2만 건이 넘는 경찰 변사 기록을 검토하고 고독사 현장을 직접 찾아다니며, 사람들이 어떻게 고립 속에서 죽음에 이르는지 추적해왔다.', NULL, NOW(6), NOW(6));
INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9788980716104', '121020', '부산광역시 강서도서관', '참외가 통통통', '한얼 (지은이)', 'https://image.aladin.co.kr/product/39782/32/cover200/8980716109_1.jpg', 0, 80, 'DEMO_SEED', '813.8-한64참', '[강서구]어린이자료실', '어느 여름날, 할아버지가 밭에서 정성껏 키운 참외를 수확하다가 어마어마하게 큰 참외를 딴다. 참외를 들고 가려는데, 아뿔싸! 떨어뜨린 참외가 통통통 비탈길을 굴러가기 시작한다. 다급한 할아버지의 외침에 고라니, 다람쥐, 개구리까지 동물들이 총출동한다. 그러나 참외는 쉽사리 잡히지 않고 점점 더 빠르게 굴려 내려간다. 마침내 참외를 손에 넣게 되는 주인공은 누구일까?', NULL, NOW(6), NOW(6));
INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9788937477478', '121020', '부산광역시 강서도서관', '악마는 열심히 산다', '김화진', 'https://shopping-phinf.pstatic.net/main_6052021/60520210427.20260619202552.jpg', 0, 80, 'DEMO_SEED', '813.6-김95악', '[강서구]종합자료실', '“악마는…… 전능하단다.”손바닥만큼 작은 몸, 화살표 꼬리, 길고 뾰족한 송곳니어느 날 내 앞에 악마가 나타나 소원을 물어본다면?노는 게 제일 좋은 장난꾸러기 악마와 은둔 청년의 엉뚱하고 비밀스러운 거래몸과 삶을 맞바꾼 후에야 비로소 알게 된내 마음, 내가 진짜로 원했던 것김화진 장편소설 『악마는 열심히 산다』가 민음사 ‘오늘의 젊은 작가’ 시리즈로 출간되었다. 첫 소설집 『나주에 대하여』로 제47회 오늘의 작가상을 수상한 김화진 소설가의 신작이다. 하나의 마음에 깃든 무수한 감정들의 행방과 변화를 세밀하게 좇는 ‘마음 탐구자’ 김화진의 탄생을 알린 첫 소설집 『나주에 대하여』 이후, 김화진은 줄곧 무한히 예측 불가한 ‘마음’에 발을 딛고 그 바깥으로 시야를 차근차근 넓혀 왔다. 연작소설 『공룡의 이동 경로』에서는 마음을 따라 움직이며 연결되는 ‘관계’의 역동을, 장편소설 『동경』에서는 우정 속에서 생동하는 이 시대 청년들의 삶과 꿈을 보여 준 소설가 김화진은 이번 소설을 통해 보다 멀고 깊은 곳으로 나아가 본다. 우리 사회에서도, 개인의 내면에서도 아득히 멀고 외진 자리, 바로 ‘고립’된 마음이다. 우리는 언제, 어떻게 혼자가 될까? 보이지 않는 곳에 숨어든 마음은 다시 연결될 수 있을까? 김화진은 우리 모두가 고립을 경험해 보았던 코로나19 팬데믹을 배경으로 그 실마리를 탐색한다. 모두가 집 밖으로 나서기 조심스러웠던 그해 초겨울, 은둔 청년 가영 앞에 작은 악마가 모습을 드러낸다. 그는 가영의 집 가장 어두운 곳에 숨어 살던 악마 Z. 악마 Z는 이 세상에서 조용히 사라지고만 싶은 가영의 마음을 읽고 거래를 제안하려 모처럼 야심 차게 등장한 참이다. 너의 남은 생을 내가 대신 살아 주겠다고. 그러나 그렇게 맞바꾼 몸, 그 몸에 딸려 온 마음속에서는 자꾸만 뜻밖의 것들이 발견된다. 악마 Z는 인간의 몸만큼이나 모든 감정을 커다랗게 느끼는 마음의 무게에, 가영은 가벼운 악마의 몸으로 옮겨 오자 가뿐히 멀어진 상처에 놀라워한다. 이 비밀스러운 거래의 유일한 목격자 종현은 오랫동안 간직해 온 자신의 비밀, 그 속에 들어 있던 소원을 발견한다. 그렇게 맞바꿀 수 없는 것을 바꿔 본 후에야, 타인을 통해 자신을 본 후에야 이들은 마주하게 된 것이다. 너무 오랫동안 숨겨져 있어서 까무룩 잊었던, 외면했던, 때로는 보고도 몰랐던 자신의 진짜 마음을.■ 인간적인 너무나 인간적인 악마 사회 “인정은 모든 악마의 둘도 없는 목표였으며 그리하여 악마들로 하여금 죽기 전에 받을 수 있을까 하고 평생을 오들오들 떨며 살아가게 하는 것이었다.” (13쪽)악마가 인간의 욕망에 맞물려 존재하듯, 소설 속 악마 사회도 인간 사회와 꼭 닮은 모습이다. 얼마나 창의적인 방법으로 악행을 저질렀는지에 따라 등급별로 업적이 나뉘고 그에 따른 포상이 이루어지는 철저한 성과 중심 사회다. 포상은 안락한 ‘집’과 뜻을 이을 ‘후손’. 그 사실을 누구보다 잘 아는 악마 Z는 전전긍긍하고 있다. 그간의 성과가 미미해, 운 좋게 얻은 보일러 있는 집을 곧 잃기 직전이기 때문이다. ‘성장하지 못하는 악마’. 그런 평가가 무엇보다 두려웠던 악마 Z는 용기를 내어 가영을 파멸로 이끌 거래를 제안한다.다만 그 거래에는 악마 Z만의 작은 즐거움이 몰래 끼어 있었다. 바로 그가 거래의 대가로 받은 가영의 스쿠터. 가영이 가진 것 중 가장 재미있어 보여 늘 탐내고 있었지만 사소한 업적이라 비난받을까 봐 외면했던 바로 그 스쿠터를 드디어 차지한 것이다. 모처럼 의욕을 낸 기념으로 스스로에게 허락한 작은 즐거움이었다. 그로부터 악마 Z에게는 새로운 즐거움이 끝말잇기 하듯 주렁주렁 밀려든다. 스쿠터, 스쿠터를 타고 달리며 듣는 음악, 음악처럼 신나게 불어오는 바람, 바람이 흐르는 골목, 골목마다 숨어 있는 맛집들. 그렇게 쌩쌩 인간 사회를 달리는 동안 악마 Z는 문득 궁금해진다. 이토록 많은 즐거움을 가영은 왜 도통 누리지 못했을까? 하고.■ 홀로 남아 소용돌이 치는 마음“진짜로 혼자가 되었을 때 가영은 마음 놓고 혼잣말에 둘러싸여 지냈다. ‘나는’과 ‘나는’ 사이에 혼자.” ', NULL, NOW(6), NOW(6));
INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9788936439972', '121020', '부산광역시 강서도서관', '아무도 미치지 않았다', '편혜영^최진영^정한아^정보라^예소연', 'https://shopping-phinf.pstatic.net/main_6067804/60678044089.20260701162153.jpg', 0, 80, 'DEMO_SEED', '813.6-편94아A', '[강서구]종합자료실', '“결심했다.어차피 평생 죄인으로 살아야 한다면진짜 죄를 지어버리자고”한국문학을 이끌어나가는 여성 소설가 5인편혜영 최진영 정한아 정보라 예소연이 그려낸‘미친 여자들’이 펼쳐 보이는 황홀한 광기의 세계우리 문단의 가장 뜨거운 이름, 편혜영 최진영 정한아 정보라 예소연 5인의 소설가가 참여한 앤솔러지 소설집 『아무도 미치지 않았다』가 출간되었다. ‘미친 여자들’이라는 주제 아래 휘몰아치는 서사로 남다른 흡인력을 보여주는 다섯편의 소설을 묶었다. 창비의 온라인 연재 플랫폼 ‘매거진창비’ 연재 당시 독자들의 열렬한 지지를 받으며 “지독히 현실적이면서 놀랍도록 서늘하다” “매 순간 차근차근 섬뜩해진다” “흩어진 퍼즐 조각이 맞춰지는 순간 소름이 끼쳤다”는 등 호평을 이끌어낸 작품들을 한층 날카롭게 벼렸다. 여성의 솔직한 욕망과 분노와 집착, 그리고 그 너머 사회구조적 문제까지 날카롭게 포착하는 아름답고도 섬뜩한 광기의 세계가 황홀하게 펼쳐진다.다섯 소설가는 모두가 미친 듯한 세상에서 실은 ‘아무도 미치지 않았다’는 메시지를 넌지시 던지며 독자로 하여금 ‘미친 여자’라는 말을 이전과는 다르게 자각하도록 만든다. 소설 속 미쳤거나 혹은 미치지 않은 인물들이 발산하는 날것의 에너지가 기존 질서에 순응하기를 거부하는 동시대 독자들에게 강렬한 해방감과 연대의 메시지를 선사할 것이다.', NULL, NOW(6), NOW(6));
INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9791173326288', '121020', '부산광역시 강서도서관', '14일', '지은이: 마거릿 애트우드,옮긴이: 남명성', 'https://image.aladin.co.kr/product/39402/13/cover200/k412139974_1.jpg', 0, 80, 'DEMO_SEED', '843-애887십', '[강서구]종합자료실', '마거릿 애트우드 책임편집미국 현대문학 대표작가 36인 참여, 초대형 문학 프로젝트!★〈BBC〉〈파이낸셜타임스〉〈코스모폴리탄〉 ‘올해의 책’ 선정★〈뉴욕타임스〉 ‘주목할 신간’ 선정 ★〈아마존〉‘에디터스 픽’ 선정 ★〈리터러리허브〉 ‘올해 가장 기대되는 책’ 선정★〈하트퍼드커런트〉 ‘주목할 기대작’ 선정★〈리더스다이제스트〉 ‘기다려지는 신간’ 선정★〈PBS〉 ‘이달의 추천 도서’ 선정★〈더메신저〉 ‘꼭 읽어야 할 책’ 10선 선정“당신은 지금 유례없이 독특한 소설 한 권을 손에 들고 있다.”부커상 수상자부터 베스트셀러 작가, 장르문학의 대가까지 전방위 거장들이 저마다의 개성으로 열어젖힌 이야기의 축제!전쟁과 재난 등 감당할 수 없는 역경과 혼란에 맞서 인간은 언제나 이야기를 만들어 절망을 딛고 다음 세대로 나아갔다. 마거릿 애트우드, 설레스트 잉, 에리카 종 등 현시대 미국을 대표하는 작가 36인이 공동으로 집필한 소설 《14일》은 문학의 시대적 소명을 유쾌하게 이어받아 팬데믹이 찾아온 뉴욕 한복판에서 이야기의 축제를 피워낸다. 참여 작가가 저마다의 등장인물을 맡아 이야기의 무대에 등장시키고 각 인물이 살아 움직이며 유기성을 만들고 서사를 쌓아나간다. 나아가 어떤 캐릭터와 어떤 파트를 담당했는지 본문이 끝난 뒤에야 밝히는 파격적인 구조로 작가의 명성에 기댄 선입견을 지운 채 오롯이 이야기에 몰입할 수 있게 한다. 다양한 인종과 세대, 문화적 배경이 각자의 글에서 고유한 문체와 상상력으로 피어오르며, 선호하는 작가가 어떤 글을 썼을지 추측하는 재미와 새로운 작가를 발견하는 쾌감을 선사한다.', NULL, NOW(6), NOW(6));
INSERT INTO hidden_books (isbn, library_code, library_name, title, author, cover, loan_count, quality_score, source, call_number, shelf_name, description, reason, created_at, updated_at) VALUES ('9791199902404', '121020', '부산광역시 강서도서관', '작고 소중한 내 돈도 불리고 싶어 주식을 시작합니다 (내 집 마련은 꿈같고, 적금은 답답하고, 손해는 겁나는 2030을 위한 친절한 주식투자)', '손희애', 'https://shopping-phinf.pstatic.net/main_6030037/60300379520.20260626154038.jpg', 0, 80, 'DEMO_SEED', '327.856-손97작', '[강서구]종합자료실', '“작지만 소중한 내 돈이라서,더 신중하게 더 제대로 시작합니다.”1,200만 뷰 경제 유튜브 ‘개념있는 희애씨’가 전하는여전히 투자가 낯선 당신을 위한 다정한 첫 주식 수업“코스피 8,000 돌파”, “사상 최고치”, “삼전·하이닉스 또 신고가” 같은 뉴스가 연일 이어지고, SNS에는 수익 인증이 넘쳐나며, 주변 사람들의 대화도 온통 주식 이야기다. 세상은 축제처럼 들썩이지만 막상 내 이야기로 가져오면 마음이 달라진다. 내 집 마련은 멀게만 느껴지고, 적금은 안전하지만 자산이 자라는 속도가 더뎌 답답하다. 다들 이제 남은 투자처는 주식뿐이라고 하지만 선뜻 시작하기 두렵다. 안 하자니 나만 제자리걸음일까 봐 불안하고, 막상 시작하자니 무엇부터 해야 할지 막막한 마음. 《작고 소중한 내 돈도 불리고 싶어 주식을 시작합니다》는 바로 그 마음에서 출발한다. 시장이 뜨거울수록 초보 투자자의 마음은 더 급해진다. 남들이 번 만큼 나도 당장 따라가야 할 것 같아 묻지마 매수나 급등주 추격에 나서기 십상이다. 하지만 이 책은 단호하게 말한다. 세상에 잃어도 괜찮은 돈은 없으며, 처음 주식을 시작하는 사람에게 가장 필요한 것은 ‘빨리 돈을 버는 법’이 아니라 ‘내 돈을 지키며 시작하는 법’이라고 말이다.유튜브 채널 〈개념있는 희애씨〉를 운영하며 현실적인 돈 관리와 재테크 이야기를 전해온 손희애 저자는 이 책에서 “나도 이제는 시작해야 할 것 같다”고 느끼는 초보 투자자들을 위해 가장 현실적인 첫 주식 로드맵을 제시한다. 내가 주식과 잘 맞는 사람인지, 남들이 하니까 따라 시작하려는 건 아닌지, 지금 내 돈의 구조가 투자해도 괜찮은 상태인지 먼저 살피게 하고, 생활비와 비상금, 저축과 투자금을 나누는 법부터 차근차근 알려준다. 이어 주식의 기본 개념, 개별주와 ETF의 차이, 좋은 회사를 보는 기준, 매수 전 확인해야 할 것들까지 초보자가 꼭 알아야 할 내용을 쉬운 언어로 풀어낸다. 나아가 ETF와 분산 투자, 소액으로 나누어 사는 방법, 월급으로 포트폴리오를 구성하는 법까지 안내한다.작고 소중한 돈이라서 더 신중하게, 하지만 더 이상 바라만 보지 않도록. 이 책은 주식 투자가 낯선 2030에게 가장 다정하고 현실적인 첫걸음이 되어줄 것이다.', NULL, NOW(6), NOW(6));

-- KDC 분류명에서 뽑은 기본 키워드. 추천 문구는 추천 시점에 AI가 만든다.
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9788964965504';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '영미문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9788964965504';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '소설' FROM hidden_books WHERE library_code = '121020' AND isbn = '9788964965504';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791167903754';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '한국문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791167903754';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '소설' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791167903754';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '종교' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791170833291';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '기독교' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791170833291';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '성서' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791170833291';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '총류' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791193939666';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '문헌정보학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791193939666';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '독서 및 정보매체의 이용' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791193939666';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '사회과학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9788964375129';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '정치학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9788964375129';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '국가와 개인 및 집단' FROM hidden_books WHERE library_code = '121020' AND isbn = '9788964375129';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '기술과학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791124121115';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '의학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791124121115';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '기초의학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791124121115';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791194828396';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '한국문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791194828396';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '소설' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791194828396';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791171259458';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '전집, 총서' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791171259458';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '기술과학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791191994513';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '가정학 및 가정생활' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791191994513';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '식품과 식료' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791191994513';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '기술과학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9788955969795';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '의학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9788955969795';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '위생학, 공공의학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9788955969795';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '총류' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791199757646';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '지식, 학문 일반' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791199757646';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791130681887';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '일본문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791130681887';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '소설' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791130681887';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791193024348';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '한국문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791193024348';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '소설' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791193024348';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791190539296';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '중국문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791190539296';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '소설' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791190539296';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '사회과학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791173326639';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '사회학, 사회문제' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791173326639';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '사회조직 및 제도' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791173326639';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9788980716104';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '한국문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9788980716104';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '소설' FROM hidden_books WHERE library_code = '121020' AND isbn = '9788980716104';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9788937477478';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '한국문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9788937477478';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '소설' FROM hidden_books WHERE library_code = '121020' AND isbn = '9788937477478';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9788936439972';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '한국문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9788936439972';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '소설' FROM hidden_books WHERE library_code = '121020' AND isbn = '9788936439972';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791173326288';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '영미문학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791173326288';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '소설' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791173326288';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '사회과학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791199902404';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '경제학' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791199902404';
INSERT INTO hidden_book_keywords (hidden_book_id, keyword) SELECT id, '금융' FROM hidden_books WHERE library_code = '121020' AND isbn = '9791199902404';
